local M = {}

vim.api.nvim_win_set_option(0, "number", true)

M.options = {
  encoding = "utf-8",
  fileencoding = "utf-8",
  termguicolors = true,
  belloff = "all",
  mouse = "a",
  tabstop = 2,
  softtabstop = 2,
  shiftwidth = 2,
  expandtab = true,
  autoindent = true,
  smartindent = true,
  smarttab = true,
  wrap = true,
  number = true,
  relativenumber = true,
  ruler = true,
  incsearch = true,
  hlsearch = true,
  ignorecase = true,
  splitbelow = true,
  splitright = true,
  backup = false,
  writebackup = false,
  showmode = false,
  cursorline = true,
  laststatus = 2,
  -- showtabline = 2,
  signcolumn = "yes",
  clipboard = "unnamedplus",
  swapfile = false,
  timeoutlen = 500,
  hidden = true,
  -- colorcolumn = "120",
  conceallevel = 0,
  completeopt = "menuone,noselect",
  -- cmdheight = 2,
}

-- M.plugins = {
--   nvim_lspconfig = true,
--   lsp_zero = true,
--   nvim_cmp = true,
--   luasnip = true,
--   mason = true,
--   mason_lsp_config = true,
--   treesitter = true,
--   autopairs = true,
--   neoformat = true,
--   telescope = true,
--   devicons = true,
--   lualine = true,
--   neotree = true,
--   bufferline = true,
--   dashboard = true,
--   tokyonight = true,
--   noice = true,
--   comment = true,
--   which_key = true,
--   toggleterm = true,
--   indent_blankline = true,
-- }

return M
