-- Package config
require("dot.packages.autopairs")
require("dot.packages.colorizer")
require("dot.packages.lualine")
require("dot.packages.mason")
require("dot.packages.neoformat")
require("dot.packages.nvimtree")
require("dot.packages.telescope")
require("dot.packages.treesitter")
require("dot.packages.toggleterm")
require("dot.packages.comment")
require("dot.packages.neorg")
