-- Package config
require("dot.plugin.autopairs")
require("dot.plugin.colorizer")
require("dot.plugin.lualine")
require("dot.plugin.mason")
require("dot.plugin.neoformat")
require("dot.plugin.nvimtree")
require("dot.plugin.telescope")
require("dot.plugin.treesitter")
require("dot.plugin.toggleterm")
require("dot.plugin.comment")
require("dot.plugin.neorg")
